import Foundation

struct Localization {
    static let startButtonTitle = NSLocalizedString("Start", comment: "Starting a new game")
    static let settingsButtonTitle = NSLocalizedString("Settings", comment: "Game settings")
    static let tryAgainButtonTitle = NSLocalizedString("Try again!", comment: "The button to start a new game after Game Over")
    static let backToMenuTitle = NSLocalizedString("Back", comment: "The button to go back to the menu screen")
    static let gameOverTitle = NSLocalizedString("Game Over", comment: "The title that indicates that the game is over")
    static let scoreLabel = NSLocalizedString("Score", comment: "The title label describing the current score")
    static let highscoreLabel = NSLocalizedString("Highscore", comment: "The title label describing the current highscore")
    static let transpositionLabel = NSLocalizedString("Transposition", comment: "The label describing the chosen transposition")
    static let useAccidentalsLabel = NSLocalizedString("Accidentals", comment: "The label describing the use of accidentals")
    static let yes = NSLocalizedString("Yes", comment: "This one kinda speaks for itself")
    static let no = NSLocalizedString("No", comment: "This one kinda speaks for itself")
    static let removeAds = NSLocalizedString("Remove Ads", comment: "Button used to pay to remove ads")
    static let purchaseFailed = NSLocalizedString("Purchase failed", comment: "Purchasing the In-App Purchase failed")
    static let ok = NSLocalizedString("OK", comment: "A general OK button")
    static let microphoneSensitivityTitle = NSLocalizedString("Microphone sensitivity", comment: "Adjusting the microphone sensitivity level")
    static let microphoneSensitivityHigh = NSLocalizedString("High", comment: "The highest level of microphone sensitivity")
    static let microphoneSensitivityMedium = NSLocalizedString("Medium", comment: "Medium level of microphone sensitivity")
    static let microphoneSensitivityLow = NSLocalizedString("Low", comment: "The lowest level of microphone sensitivity")
    static let b = NSLocalizedString("B", comment: "The note B. This is H in Norwegian")
    static let restorePurchases = NSLocalizedString("Restore purchases", comment: "The button to restore previous purchases")
    static let restorePurchasesText = NSLocalizedString("Are you sure you want to restore all previous purchases?", comment: "If the user deletes the app / get's a new device etc, this button can be pressed to restore all previous purchases")
    static let purchasesRestored = NSLocalizedString("Purchases restored successfully!", comment: "Title for Purchases restored successfully dialogue box")
    static let purchasesRestoredText = NSLocalizedString("All previous purchases have been restored.", comment: "Body for Purchases restored successfully dialogue box")
    static let leaderboardsTitle = NSLocalizedString("Leaderboards", comment: "Button title for Game Center leaderboards")
    static let info = NSLocalizedString("Info", comment: "Title for info button")
}
